### ISSUE TITLE
Уточнить средства мониторинга

### ISSUE THREAD

**Issue by Justarone** [iu7og/bongodb#12]
Чтобы закрыть задачу нужно сделать:

- [x]  ответить на вопрос: какие метрики будут собираться? (выделить минимальный набор метрик из похожих продуктов).
- [x]  ответить на вопрос: как метрики будут собираться? частично есть в [тикете с архитектурой](https://github.com/iu7og/bongodb/issues/7).
- [x]  ответить на вопрос: как логи будут собираться? частично есть в [тикете с архитектурой](https://github.com/iu7og/bongodb/issues/7).
- [x]  добавить информацию в [ТЗ](https://github.com/iu7og/bongodb/wiki/%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5) и в [тикет с архитектурой](https://github.com/iu7og/bongodb/issues/7).

**Comment by hackfeed** [comment]
### Собираемые метрики

Для оценки состояния кластера стоит собирать:
* Количество подключенных клиентов (по всему кластеру)
* Использование процессора (%) (по каждой ноде)
* Использование памяти (выделенная, реально используемая) (по каждой ноде)
* Количество исполняемых команд за единицу времени (по каждой ноде)
* Количество исполняемых команд на команду за единицу времени (сколько получений, сколько записей и т.п.) (по всему кластеру)
* Задержка при исполнении команд (по каждой ноде)
* Задержка при исполнении команд на команду (по каждой ноде)
* Хит/мисс рейт (по каждой ноде)
* Количество ключей (по каждой ноде)
* Количество истекших ключей (по каждой ноде)

Касаемо необходимости каждой метрики можно почитать [тут](https://www.datadoghq.com/pdf/Understanding-the-Top-5-Redis-Performance-Metrics.pdf). Если вкратце -- такая совокупность метрик может сузить кругозор поиска узкого места системы, в котором произошел сбой -> сокращается время на устранение неполадки.

### Способ сбора метрик

Предлагаю не использовать graphite, так как я вообще не понял зачем он нужен, там какой-то миллион наворотов и зависимостей. Вместо него предлагаю использовать [Prometheus](https://prometheus.io/docs/introduction/overview/). Ему не нужно миллион зависимостей, для него есть C++ [инструмент](https://github.com/jupp0r/prometheus-cpp) для экспорта метрик + я умею дружить Prometheus с Grafana для мониторинга.

### Способ сбора логов

Для логирования предлагаю использовать C++ [graylog-logger](https://github.com/ess-dmsc/graylog-logger). Он позволяет собирать логи в консоль, файл, а что самое главное, экспортировать их через UDP по протоколу GELF в Graylog (Grafana для логов).

### Итог 

Таким образом, можно собирать метрики и логи внутри core-кода, экспортировать их в Prometheus (метрики) и GELF (логи) форматах и не использовать самописные тулзы для визуализации, а использовать проверенные и хорошо документированные инструменты, что значительно сократит время разработки CLI приложения, но добавит работы core-команде (но не особо сильно, так как все равно предполагалось легирование + сбор метрик на уровне core-кода. Просто придется разобраться в новых инструментах (библиотеках) для логирования и сбора метрик).

**Comment by Justarone** [comment]
> Количество подключенных клиентов

Могут быть сложности с учетом использования grpc сервера, надо погуглить, есть ли такое в cpp в том, что он там кодгенит.

> Команда на команду

Звучит сильно, но я вроде понял. Речь про операцию ведь? Чтение/Запись? Есть средняя задержка на вообще любую команду, а это средняя задержка на класс команд (то есть на все чтения), так?

> Количество истекший ключей

Что? Кто?...........

![img](https://alittlebit.ru/upload/iblock/197/12126e8ccd7ac3069b2db37dc4e46e89.jpeg)

Prometheus - OK
graylog - что-то какое-то очень непопулярное решение, на стороне core тяжко будет найти поддержку, если что-то пойдет не так (10 звездочек на GH). Это точно самое распространенное? + я не уверен, что стоит импорт логов через udp пихать в core, я бы взял более популярный логгер на уровне cpp и писал бы в файл, а импорт на совесть инфраструктуры оставил бы..

Давай еще обсудим импорт логов, пожалуйста

**Comment by hackfeed** [comment]
> надо погуглить, есть ли такое в cpp

Посмотрел, ты прав, возможности из коробки считать количество подключенных клиентов нет, поэтому, думаю, считать это не стоит, не такая уж важная информация.

> средняя задержка на класс команд

Да, все так.

> Что? Кто?...........

Редис умеет считать количество ключей, у которых истек TTL. Можем по такому количеству ключей посмотреть, когда истекли и сколько ключей, чтобы отловить какую-нибудь ошибку.

> Давай еще обсудим импорт логов, пожалуйста

По поводу импорта логов: можно использовать [spdlog](https://github.com/gabime/spdlog) и не смотреть в сторону грейлога, но тогда придется мержить логи, записанные в файл, с разных подов по времени. Возможно это не такая уж и большая проблема (если у нас вообще стоит цель централизации логов).

**Comment by Justarone** [comment]
По поводу TTL и временных ключей - пока подожди, я не знал, что это планируется. Возможно, это может повлиять на контейнеры, на исследования, надо коллективно обсужить, нужно ли нам это.

С либой для логов согласен, выглядит чуть привлекательнее. По поводу централизации - я думаю, что централизация нужна в смысле возможности сбора логов со всех нод в одном месте, а не в смысле отображения всех сразу (хотя тоже желательно). Если ты хочешь не джейсоны парсить, а какой-нибудь бинарный протокол - я думаю, мы сможем вчетвером что-то сваять (логгер очень не сложно и не долго пишется), но по-моему джейсонов должно хватить для этих целей.

**Comment by hackfeed** [comment]
По-моему инмемори KV без TTL не имеет смысла. Можно залить базу юзлесс данными и что мы будем делать, когда кончится оперативка?

**Comment by Justarone** [comment]
Я думал, что будет удаление

**Comment by hackfeed** [comment]
Удаление то тоже будет, но ладно, думаю, TTL не супер прям роляет, можем и опустить

**Comment by Justarone** [comment]
Кажется, что по данному тикету от тебя требуется:
* Уточнить, как будет происходить сбор логов из файлика на 1 ноду (хотя бы примерно)
* будет ли мерж (+ сорт) логов или они отдельные будут?
* Какой формат ты хочешь от core?

**Comment by hackfeed** [comment]
1. spdlog умеет писать в syslog. Пишите и в файл, и в syslog, тогда я просто из CLI смогу дергать syslog, чтобы не прерывать запись в файл.
2. Мерж и сорт будут, иначе смысла в этом особо нет. Думаю, что еще добавлю просто флажок для отображения логов по отдельной ноде
3. Формат мне в принципе не важен. Главное, чтобы была возможность распарсить таймстемп для последующего мержа

**Comment by Justarone** [comment]
Мне кажется, что нет проблем, если ты откроешь файл на чтение и будешь мониторить (прерывания не будет) или я что-то не понимаю?

**Comment by hackfeed** [comment]
Разве я буду видеть, что в него дописывается..?

**Comment by Justarone** [comment]
Вопрос хороший надо проверить (в любом случае в сислог тоже можем писать, поэтому вопросов больше нет, наверное, этот момент уже в процессе ты уладишь)
